### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by ecr23xx** [facebookresearch/video-long-term-feature-banks#19]
When loading AVA R50 baseline pre-trained model for training, it raises the error displayed below.

```
[INFO: checkpoints.py:  198]: Resume training: False
[INFO: checkpoints.py:  150]: Coverting model : data/models/ava/r50_baseline.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 241, in <module>
    main()
  File "tools/train_net.py", line 237, in main
    train(args)
  File "tools/train_net.py", line 141, in train
    start_model_iter = checkpoints.load_model_from_params_file(train_model)
  File "/path/to/lfb/lib/utils/checkpoints.py", line 203, in load_model_from_params_file
    converted_checkpoint = convert_model(cfg.TRAIN.PARAMS_FILE)
  File "/path/to/lfb/lib/utils/checkpoints.py", line 155, in convert_model
    ori_blobs = load_and_convert_caffe2_cls_model(model_path)
  File "/path/to/lfb/lib/utils/checkpoints.py", line 145, in load_and_convert_caffe2_cls_model
    remove_spatial_bn_layers(c2cls_weights)
  File "/path/to/lfb/lib/utils/checkpoints.py", line 105, in remove_spatial_bn_layers
    bn_mean = c2cls_weights['blobs'][name_rm]
KeyError: u'nonlocal_conv3_1_bn_rm'
```

Could you explain how to solve this problem? My running script is 

```bash
python2 tools/train_net.py \
  --config_file configs/ava/r50_baseline.yaml \
  NUM_GPUS 4 \
  TRAIN.BATCH_SIZE 8 \
  TEST.BATCH_SIZE 8 \
  TRAIN.PARAMS_FILE data/models/ava/r50_baseline.pkl \
  CHECKPOINT.DIR logs/ava/r50_baseline
```

The config file I use is [configs/ava_r50_baseline.yaml](https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/configs/ava_r50_baseline.yaml).

**Comment by chaoyuaw** [comment]
Hi @ecr23xx, 

Short answer:
This error happens when you set CHECKPOINT.CONVERT_MODEL to be True to convert a model's BN layers to Affine layers (to "freeze" BN layers), but the model already has all BN converted to Affine already.

More detailed answer:
The training script assumes training from a Kinetics-pretrained weight file downloaded from https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/GETTING_STARTED.md#download-pre-trained-weights
The pre-trained model was pre-trained using BN, so we set CHECKPOINT.CONVERT_MODEL to be True to convert BN layers to Affine layers. This essentially freezes the BN layers.

It looks like your TRAIN.PARAMS_FILE is set to be the final weight file downloaded from 
https://github.com/facebookresearch/video-long-term-feature-banks#ava
This model has already converted BN to Affine and has been already trained on AVA. This model should not require further training on AVA. But if you still want to continue training, you could set CHECKPOINT.CONVERT_MODEL to be False to avoid converting twice and cause the error. 

Please feel free to let me know if you have further questions :) Thanks!

**Comment by chaoyuaw** [comment]
Just a friendly reminder: if you use a different batch size or different number of GPUs, the schedule and learning rate needs to be adjusted using "linear scaling rule" (https://arxiv.org/abs/1706.02677) to reproduce the results.

**Comment by ecr23xx** [comment]
Thank you!
